### ISSUE TITLE
No video with supported format and MIME type found

### ISSUE THREAD

**Issue by 99991** [zliucz/animate-your-word#1]
On Firefox, the video on your demo page says

> No video with supported format and MIME type found

Assuming you used ffmpeg to process the video, you can probably fix this by adding `-pix_fmt yuv420p` to your ffmpeg invocation: https://stackoverflow.com/a/24468585

![unsupported](https://github.com/zliucz/animate-your-word/assets/18725165/56191508-9f4a-4548-93be-fffdcc33314e)

**Comment by bruceyyu** [comment]
@99991 thanks for reporting this bug!
We didn't know Firefox doesn't support HEVC encoding, sorry... We've changed our video to H.264, and it should work on Firefox now!

**Comment by 99991** [comment]
Great, it works now. Thank you!
