### ISSUE TITLE
model link  is not available

### ISSUE THREAD

**Issue by zh2010** [zliucz/animate-your-word#3]
damo-vilab/text-to-video-ms-1.7b  is not available，can't run your code :
CUDA_VISIBLE_DEVICES=0 python dynamicTypography.py \
        --word "father" --optimized_letter "h" \
        --caption "A tall father walks along the road, holding his little son with his hand" \
        --use_xformer --canonical --anneal \
        --use_perceptual_loss --use_conformal_loss \
        --use_transition_loss

**Comment by zliucz** [comment]
Hi there :). Maybe you can try to change the model name to ali-vilab/text-to-video-ms-1.7b. Let me know if this works. Thanks.

**Comment by zh2010** [comment]
> Hi there :). Maybe you can try to change the model name to ali-vilab/text-to-video-ms-1.7b. Let me know if this works. Thanks.

I replace ali-vilab/text-to-video-ms-1.7b in dynamicTypography.py. Then I run 
CUDA_VISIBLE_DEVICES=0 python dynamicTypography.py
--word "father" --optimized_letter "h"
--caption "A tall father walks along the road, holding his little son with his hand"
--use_xformer --canonical --anneal
--use_perceptual_loss --use_conformal_loss
--use_transition_loss

show the error:Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/ali-vilab/text-to-video-ms-1.7b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26dfbfaac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 0dcc6c7a-ed37-4631-833d-b4570c9ef825)').
Will try to load from local cache.   

but I can visit huggingface on my brower
.

**Comment by zliucz** [comment]
It seems that you got a connection error. I'm sorry that this is not our code's problem :(. 

There may be something wrong with your proxy. You may find https://github.com/huggingface/transformers/issues/17611 helpful. Thanks.
